mastersedder/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('mastersedder/', include('mastersedderapp.urls')),
    path('admin/', admin.site.urls),
]

mastersedderapp/urls.py
from django.urls import path

from . import views

app_name = 'mastersedderapp'
urlpatterns = [
	# ex: /mastersedder/
	path('', views.IndexView.as_view(), name='index'),
	# ex: /mastersedder/about/
	path('about/', views.AboutView.as_view(), name='about'),
	# ex: /mastersedder/5/
	path('<int:pk>/', views.DetailView.as_view(), name='detail'),
	# ex: /mastersedder/5/results/
	path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
	# ex: /mastersedder/5/vote/
	path('<int:question_id>/vote/', views.vote, name='vote'),
]

mastersedderapp/models.py
import datetime
from django.db import models
from django.utils import timezone

# Create your models here.

class Question(models.Model):
	question_text = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published')
	def __str__(self):
		return self.question_text
	def was_published_recently(self):
		now = timezone.now()
		return now - datetime.timedelta(days=1) <= self.pub_date <= now
	was_published_recently.admin_order_field = 'pub_date'
	was_published_recently.boolean = True
	was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)
	def __str__(self):
		return self.choice_text

mastersedderapp/views.py
from django.http import Http404
from django.shortcuts import get_object_or_404, render
from django.utils import timezone

# Create your views here.
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from django.views import generic

from .models import Choice, Question


class IndexView(generic.ListView):
	template_name = 'mastersedderapp/index.html'
	context_object_name = 'latest_question_list'

	def get_queryset(self):
		"""
		Return the last five published questions (not including those set to be
		published in the future).
		"""
		return Question.objects.filter(
			pub_date__lte=timezone.now()
		).order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
	model = Question
	template_name = 'mastersedderapp/detail.html'

	def get_queryset(self):
		"""
		Excludes any questions that aren't published yet.
		"""
		return Question.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
	model = Question
	template_name = 'mastersedderapp/results.html'

class AboutView(generic.ListView):
	model = Question
	template_name = 'mastersedderapp/about.html'

def vote(request, question_id):
	#return HttpResponse("You're voting on question %s." % question_id)

	question = get_object_or_404(Question, pk=question_id)
	try:
		selected_choice = question.choice_set.get(pk=request.POST['choice'])
	except (KeyError, Choice.DoesNotExist):
		# Redisplay the question voting form.
		return render(request, 'mastersedderapp/detail.html', {
			'question': question,
			'error_message': "You didn't select a choice.",
		})
	else:
		selected_choice.votes += 1
		selected_choice.save()
		# Always return an HttpResponseRedirect after successfully dealing
		# with POST data. This prevents data from being posted twice if a
		# user hits the Back button.
	return HttpResponseRedirect(reverse('mastersedderapp:results', args=(question.id,)))

mastersedderapp/templates/base.html
{% load staticfiles %}
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Mastersedder</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <style type="text/css">
body {
  padding-top: 50px;
}
    </style>
  </head>

  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'mastersedderapp:index' %}">Mastersedder</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="{% block nav_MSs %}{% endblock %}"><a href="{% url 'mastersedderapp:index' %}">Mastersedder</a></li>
            <li class="{% block nav_about %}{% endblock %}"><a href="{% url 'mastersedderapp:about' %}">About</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">
    {% bootstrap_messages messages %}
    {% block contents %}{% endblock %}
    </div><!-- /.container -->

<footer class="footer">
  <div class="container"><br><br><br><br><hr>
    <p class="text-muted">Copyright &copy;  2019  jinsiben</p>
  </div>
</footer>
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>
</html>

mastersedderapp/templates/mastersedderapp/about.html
{% extends "base.html" %}

{% block contents %}
<h1>About Mastersedder</h1>


<h2>sed - stream editor</h2>
<h3>学習用クイズサイト[予定]</h3>

<p>
<ul><li>sed [stream editor] 学習用クイズサイト[予定]</li></ul>
</p>


<h3>環境</h3>
<p>
<ul><li>GNU sed 4.2.2</li></ul>
</p>



<h3>免責事項</h3>
<p>
<ul>
<li>当サイトの作成者は、当サイトの利用によって生じたあらゆる損害に対して、一切の責任を負いません。</li>
<li>当サイトの内容は予告なしに変更されることがあります。</li>
<li>当サイトのサービスは予告なしに停止されることがあります。</li>
</ul>
</p>

<h3>コンタクト</h3>
<p>
<ul><li>jinsiben+ms[at]gmail.com</li></ul>
</p>
{% endblock contents %}

mastersedderapp/templates/mastersedderapp/detail.html
{% extends "base.html" %}
{% load bootstrap3 %}


{% block contents %}
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'mastersedderapp:vote' question.id %}" method="post" class="form">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}

</form>

{% endblock contents %}

mastersedderapp/templates/mastersedderapp/index.html
{% extends "base.html" %}
{% load static %}
{% load staticfiles %}
<html>
<link rel="stylesheet" type="text/css" href="{% static 'mastersedderapp/style.css' %}">
  <head> <!-- ← 追加 -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" /> <!-- ← 追加 -->
  </head> <!-- ← 追加 -->
<body>

{% block contents %}

<h1>MasterSedder</h1>



{% if latest_question_list %}
<div class="table-responsive">
<table  class="table table-hover">
    <tr>
      <th>ID</th>
      <th>内容</th>
      <th>登録日時</th>
    </tr>

    {% for question in latest_question_list %}
    <tr>
	<td>{{ question.id }}</td>
        <td><a href="{% url 'mastersedderapp:detail' question.id %}">{{ question.question_text }}</a></td>
	<td>{{ question.pub_date }}</td>
    {% endfor %}
    </tr>
</table>
</div>
{% else %}
    <p>No MSs are available.</p>
{% endif %}

{% endblock contents %}

</body>

</html>

mastersedderapp/templates/mastersedderapp/results.html
{% extends "base.html" %}

{% block contents %}
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>
<hr>
<a href="{% url 'mastersedderapp:detail' question.id %}">Vote again?</a>


{% endblock contents %}